// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Feed struct {
	FeedName     string
	LatestCursor sql.NullInt64
}

type FeedPost struct {
	FeedName string
	TimeUs   int64
	Did      string
	Rkey     string
}
